title: Startups of Shoreditch # The title of the pages
theme: basic # The theme (from the themes directory)
game_type: startups # The gametype (from the games directory)

header: "JS Competition"
description: "This is a test of an in-progress JS competition engine"